application: lobster-nachos
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /static
  static_dir: static

- url: /.*
  script: main.application

- url: /mysql2
  script: app.app

- url: /mysql
  script: app_mysql.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: django
  version: "latest"
- name: MySQLdb
  version: "latest"

env_variables:
  DJANGO_SETTINGS_MODULE: 'Django_AppEngine.settings'
