application: lobster-nachos
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /static
  static_dir: static

- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: django
  version: "1.4"

env_variables:
  DJANGO_SETTINGS_MODULE: 'Django_AppEngine.settings'
